# Use root/example as user/password credentials
version: '3.1'

services:
 db:
    # In production, you may want to use a managed database service
    image: postgres:9.6-alpine
    labels:
      - "traefik.frontend.rule=Host:db.localhost"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=coucou
    #volumes:
      #- db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"