# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: mehdibg92
      MYSQL_DATABASE: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
